###################################################################################
#
# Konfigurasi hostapd.conf
#
###################################################################################

ctrl_interface=/var/run/hostapd
ctrl_interface_group=0

# Driver Wi-Fi
driver=nl80211

# Konfigurasi jaringan
ssid=hostapd
hw_mode=g
channel=11
country_code=ID
ignore_broadcast_ssid=0

#----------------------------------------------------------------------------------
# OPN
#----------------------------------------------------------------------------------
#auth_algs=1
#wpa=0

#----------------------------------------------------------------------------------
# WEP
#----------------------------------------------------------------------------------
#auth_algs=1
#wep_key0=[password]
#wep_default_key=0

#----------------------------------------------------------------------------------
# WPA-PSK
#----------------------------------------------------------------------------------
#auth_algs=1
#wpa=1
#wpa_key_mgmt=WPA-PSK
#wpa_pairwise=TKIP
#wpa_passphrase=[password]

#----------------------------------------------------------------------------------
# WPA2-PSK
#----------------------------------------------------------------------------------
auth_algs=1
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
wpa_passphrase=12345678
ieee80211w=1

#----------------------------------------------------------------------------------
# WPA2-PSK-SHA256
#----------------------------------------------------------------------------------
#auth_algs=1
#wpa=2
#wpa_key_mgmt=WPA-PSK-SHA256
#rsn_pairwise=CCMP
#wpa_passphrase=[password]
#ieee80211w=2

#----------------------------------------------------------------------------------
# Mixed Mode
#----------------------------------------------------------------------------------
#auth_algs=1
#wpa=3
#wpa_key_mgmt=WPA-PSK
#wpa_pairwise=TKIP
#rsn_pairwise=CCMP
#wpa_passphrase=[password]
#ieee80211w=1

#----------------------------------------------------------------------------------
# Transition Mode
#----------------------------------------------------------------------------------
#auth_algs=1
#wpa=2
#wpa_key_mgmt=WPA-PSK SAE
#rsn_pairwise=CCMP GCMP
#wpa_passphrase=[password]
#sae_password=[password]
#ieee80211w=1

#----------------------------------------------------------------------------------
# WPA3-SAE
#----------------------------------------------------------------------------------
#auth_algs=1
#wpa=2
#wpa_key_mgmt=SAE
#rsn_pairwise=GCMP
#sae_password=[password]
#ieee80211w=2

#----------------------------------------------------------------------------------
# OWE
#----------------------------------------------------------------------------------
#auth_algs=1
#wpa=2
#wpa_key_mgmt=OWE
#rsn_pairwise=GCMP
#ieee80211w=2
